In [1]:
from transformers import AutoTokenizer
import pandas as pd
import csv
import os
import numpy as np
from glob import glob
from transformers import AutoModelForTokenClassification, DistilBertForTokenClassification, TrainingArguments, Trainer, DataCollatorForTokenClassification
import torch
from source.eval import evaluate_indices, score
from sklearn.metrics import classification_report, f1_score, accuracy_score, precision_score, recall_score 
from sklearn.preprocessing import MultiLabelBinarizer
from torch import nn

In [2]:
! CUDA_VISIBLE_DEVICES=0
import os
os.environ["NCCL_P2P_DISABLE"]="1"
os.environ["NCCL_IB_DISABLE"]="1"

In [3]:
#os.environ["CUDA_VISIBLE_DEVICES"]='1'

In [4]:
name_model="google-bert/bert-base-cased"

In [5]:
tokenizer = AutoTokenizer.from_pretrained(name_model, padding='max_length')

In [6]:
sent = "This is, a real; sentence. Not really Legal...\nBut it is\nok."
tok_sent = tokenizer(sent)
print(tok_sent)
tokens = tokenizer.convert_ids_to_tokens(tok_sent["input_ids"])
print(tokens)

{'input_ids': [101, 1188, 1110, 117, 170, 1842, 132, 5650, 119, 1753, 1541, 10800, 119, 119, 119, 1252, 1122, 1110, 21534, 119, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
['[CLS]', 'This', 'is', ',', 'a', 'real', ';', 'sentence', '.', 'Not', 'really', 'Legal', '.', '.', '.', 'But', 'it', 'is', 'ok', '.', '[SEP]']


In [7]:
files = glob("./documents/lines/train/*.txt")
dataset_train = []
for file in files: 
    text = open(file, "r")
    original = text.readlines()
    for i in range(len(original)):
        original[i]= original[i].strip('\n')
        dataset_train += [original[i]]

In [8]:
files = glob("./documents/lines/dev/*.txt")
dataset_dev = []
for file in files: 
    text = open(file, "r")
    original = text.readlines()
    for i in range(len(original)):
        original[i]= original[i].strip('\n')
        dataset_dev += [original[i]]

In [9]:
files = glob("./documents/lines/test/*.txt")
dataset_test = []
for file in files: 
    text = open(file, "r")
    original = text.readlines()
    for i in range(len(original)):
        original[i]= original[i].strip('\n')
        dataset_test += [original[i]]

In [10]:
df = pd.read_csv("./dataset_v20230110.tsv", delimiter="	", quoting=csv.QUOTE_NONE, encoding='utf-8')
df.head()

document                                            content  \
0  ROSENBLATT v. BAER_MCL  MR. JUSTICE BRENNAN delivered the opinion of t...   
1  ROSENBLATT v. BAER_MCL  A jury in New Hampshire Superior Court awarded...   
2  ROSENBLATT v. BAER_MCL  Respondent alleged that the column contained d...   
3  ROSENBLATT v. BAER_MCL  In the interval between the trial and the deci...   
4  ROSENBLATT v. BAER_MCL  We there held that consistent with the First a...   

                                tag  
0               Announcing function  
1  Describing the adjudicated facts  
2      Describing procedural events  
3  Describing the adjudicated facts  
4       Recalling a SCOTUS decision

In [11]:
def add_classes(ner_tags, nb_spans):
    indexes = np.where(ner_tags == 0)[0]

    #print("indexes : ", indexes)
    #print("ner_tags : ", ner_tags)
    start = 0
    #print(ner_tags)
    for i in indexes:
        #print(start, i)
        ner_tags[start:i] = make_span(ner_tags[start:i], nb_spans)
        start = i + 1
    return ner_tags

def make_span(span, nb_spans):
    start = 0
    for i in range(1,nb_spans+1):
        offset = (int(len(span)/nb_spans))+start
        
        if len(span) - offset < nb_spans:
            offset = len(span)
        span[start:offset+1] = i
        #print(offset)
        start = offset
        #print("span : ",span)
    
    return span


In [12]:
def make_dataset(dataset, nb_spans,return_tensors=None):
    sentences = []
    ner_tags = []
    fin_tags = []
    tokenizeds = []

    for i in range(len(dataset)):
        tok_sent = tokenizer(dataset[i], return_offsets_mapping=True)
        #print(type(tok_sent))
        #print(tok_sent['offset_mapping'])
        tokens = tokenizer.convert_ids_to_tokens(tok_sent["input_ids"])
        sentences += tokens[1:-1]
        n_tag = np.zeros(len(tokens), dtype=int)
        n_tag[-1] = 1
        ner_tags += n_tag.tolist()
        tok_sent["labels"] = n_tag
        #tokenizeds_dev+= [tok_sent]
    ner_tags = (np.array(ner_tags) - 1) * (-1) 
    ner_tags = add_classes(np.array(ner_tags), nb_spans)
    print(ner_tags)
    ner_tags = [t for t in ner_tags]
    for i in range(0, len(sentences), (507)):
        if i + 507 > len(sentences):
            tokens = ['CLS'] + sentences[i:len(sentences)] + ['SEP']
            fin_tags = [-100] + ner_tags[i:len(sentences)] + [-100]
        else : 
            tokens = ['CLS'] + sentences[i:i + 507] + ['SEP']
            fin_tags = [-100] + ner_tags[i:i + 507] + [-100]
        #print(tokenizer.convert_tokens_to_string(tokens))
        sent = tokenizer.decode(tokenizer.convert_tokens_to_ids(tokens[1:-1]))
        #print(type(sent))
        tokeniz = tokenizer(sent, return_tensors=return_tensors)
        #print(tokenizer.convert_tokens_to_string(tokeniz))
        #print(tokeniz)
        tokeniz["labels"] = fin_tags
        #print(fin_tags)
        #print('input_ids : ', len(tokeniz['input_ids']))
        #print('input_ids : ', tokeniz['input_ids'])
        #print(sent)
        #print('labels :', len(tokeniz['labels']))
        #print('am : ', len(tokeniz['attention_mask']))
        tokenizeds += [tokeniz]
    
    return tokenizeds
nb_spans = 10
tokenizeds_dev = make_dataset(dataset_dev, nb_spans)
tokenizeds_train = make_dataset(dataset_train, nb_spans)
tokenizeds_test = make_dataset(dataset_test, nb_spans, return_tensors="pt")

[1 2 3 ... 3 3 0]
[1 2 3 ... 1 1 0]
[1 2 3 ... 1 1 0]


In [25]:
print(tokenizeds_dev[0]['labels'])

[-100, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 

In [14]:
label_list = [str(s) for s in range(0,nb_spans+1)]

In [15]:
id2label = {int(s):s for s in label_list}
print(id2label)
label2id = {s:int(s) for s in label_list}
print(label2id)

{0: '0', 1: '1', 2: '2', 3: '3', 4: '4', 5: '5', 6: '6', 7: '7', 8: '8', 9: '9', 10: '10'}
{'0': 0, '1': 1, '2': 2, '3': 3, '4': 4, '5': 5, '6': 6, '7': 7, '8': 8, '9': 9, '10': 10}


In [16]:
"""
id2label = {
    0: "0",
    1: "1"
}

label2id = {
    "0": 0,
    "1": 1
}
"""

'\nid2label = {\n    0: "0",\n    1: "1"\n}\n\nlabel2id = {\n    "0": 0,\n    "1": 1\n}\n'

In [17]:
model = AutoModelForTokenClassification.from_pretrained(
        name_model, 
        num_labels=nb_spans+1, 
        id2label=id2label, 
        label2id=label2id)
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)

Some weights of BertForTokenClassification were not initialized from the model checkpoint at google-bert/bert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [18]:
import evaluate

seqeval = evaluate.load("seqeval")

In [19]:
def compute_metrics(p):

    predictions, labels = p
    predictions = np.argmax(predictions, axis=2)

    true_predictions = []
    true_labels = []

        

    for prediction, label in zip(predictions, labels):
        for (p, l) in zip(prediction, label) :
            if l != -100:
                true_predictions += [label_list[p]]
                true_labels += [label_list[l]]
    
    #for prediction, label in zip(predictions, labels):
    #    for (p, l) in zip(prediction, label) :
    #        if l != -100:
    #            true_labels += [label_list[p]]
    """
    true_labels = [

        [label_list[l] for (p, l) in zip(prediction, label) if l != -100]

        for prediction, label in zip(predictions, labels)

    ]


    true_labels = [ l for l in true_labels]
    true_predictions = [ l for l in true_predictions]
    #print(len(true_predictions))
    #print(len(true_labels))
    """
    """
    l_pre = []
    l_rec = []
    l_f1 = []

    for p, l in zip(true_predictions, true_labels):
        p = np.array(p, dtype=int)
        l = np.array(l, dtype=int)
        tp = len(np.where((p == l) and (p == 0))[0])
        tn = len(np.where((p == l) and (p != 0))[0])
        fp = len(np.where((p != l) and (p == 0))[0])
        fn = len(np.where((p != l) and (p != 0)[0]))
        pre, rec, f1 = score(tp, fp, fn)
        l_pre += [pre] 
        l_rec += [rec] 
        l_f1 += [f1] 
    """
    
    MultiLabelBinarizer()

    return {

        "precision": precision_score(true_labels, true_predictions, average='macro', zero_division=0),

        "recall": recall_score(true_labels, true_predictions, average='macro', zero_division=0),

        "f1": f1_score(true_labels, true_predictions, average='macro', zero_division=0),

        "accuracy": accuracy_score(true_labels, true_predictions),

    }

    

    '''
    for p, l in zip(true_predictions, true_labels):
        pred = list(np.where(np.array(p) == '1')[0])
        lab = list(np.where(np.array(l) == '1')[0])
        pre, rec, f1 = evaluate_indices(lab, pred)
        #acc = 
        if len(np.unique(l)) == 2:
            l_pre += [pre]
            l_rec += [rec]
            l_f1 += [f1]
           # l_acc += [acc]
        else : 
            l_pre += [1]
            l_rec += [1]
            l_f1 += [1]
           # l_acc += [acc]

    return {

        "precision": np.mean(l_pre),

        "recall": np.mean(l_rec),

        "f1": np.mean(l_f1),

        "accuracy": np.mean(l_pre),

    }
    '''
    #print(evaluate_indices)
    results = seqeval.compute(predictions=true_predictions, references=true_labels, zero_division=0)

    return {

        "precision": results["overall_precision"],

        "recall": results["overall_recall"],

        "f1": results["overall_f1"],

        "accuracy": results["overall_accuracy"],

    }

In [20]:
class CustomTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.pop("labels")
        # forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")
        # compute custom loss (suppose one has 2 labels with different weights)
        #loss_fct = nn.CrossEntropyLoss(weight=torch.tensor([0.6 , 0.05]).to('cuda'))
        loss_fct = nn.CrossEntropyLoss(weight=torch.tensor([3,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05,0.05]).to('cuda'))
        #print(len(logits.view(-1, self.model.config.num_labels)))
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

In [21]:
training_args = TrainingArguments(
    output_dir="./models/bert-v0",
    learning_rate=2e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=10,
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True
)

trainer = Trainer(
    model=model,#.to('cuda'),
    args=training_args,
    train_dataset=tokenizeds_train,
    eval_dataset=tokenizeds_dev,
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

trainer.train()

KeyboardInterrupt: 

In [ ]:
#import huggingface_hub
#huggingface_hub.login(token='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')
#trainer.push_to_hub("distilber for tok classif")


In [ ]:
print(tokenizeds_dev[0].keys())

dict_keys(['input_ids', 'token_type_ids', 'attention_mask', 'labels'])


In [ ]:
model = AutoModelForTokenClassification.from_pretrained("./models/bert-v0/checkpoint-290")
labels = []
tok_labels = []
for x in tokenizeds_test:
    #print(x['input_ids'])
    inputs = {}
    #print(x.keys())
    #print(x['input_ids'][0])
    #print(tokenizer.decode(x['input_ids'][0]))
    inputs['input_ids'] = x['input_ids']
    inputs['attention_mask'] = x['attention_mask']
    with torch.no_grad():
        logits = model(**inputs).logits
    #print(logits)

    

    predicted_token_class_ids = logits.argmax(-1)
    print(np.unique(predicted_token_class_ids))
    predicted_tokens_classes = [model.config.id2label[t.item()] for t in predicted_token_class_ids[0]]
    labels += predicted_token_class_ids.tolist()
    print(labels[-1])
    print(x.labels)

    idx = np.where(x.labels == 0)
    idx2 = np.where(labels[-1] == 0)
    tok_labels += [x['labels']]


idx = np.where(labels == 0)
idx2 = np.where(tok_labels == 0)

[ 1  2  3  4  5  6  7  8  9 10]
[9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 8, 3, 1, 1, 1, 1, 7, 8, 8, 8, 8, 8, 8, 8, 1, 8, 8, 6, 8, 8, 8, 1, 8, 6, 6, 1, 8, 3, 5, 9, 9, 9, 9, 9, 9, 9, 1, 5, 7, 9, 5, 8, 10, 10, 10, 10, 10, 10, 10, 10, 6, 6, 10, 5, 6, 10, 10, 4, 10, 10, 6, 10, 10, 6, 6, 9, 9, 6, 7, 7, 5, 9, 9, 9, 9, 9, 9, 9, 1, 2, 8, 8, 5, 5, 8, 5, 4, 8, 5, 2, 10, 8, 8, 8, 8, 9, 9, 8, 4, 3, 3, 6, 5, 3, 6, 9, 2, 5, 8, 3, 7, 8, 4, 6, 8, 8, 8, 8, 6, 8, 3, 2, 8, 9, 8, 8, 7, 2, 7, 7, 8, 8, 9, 9, 8, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 4, 2, 6, 3, 3, 3, 1, 2, 2, 7, 4, 4, 6, 9, 6, 6, 9, 9, 1, 2, 7, 1, 2, 2, 8, 1, 8, 2, 2, 8, 8, 4, 8, 3, 8, 8, 9, 9, 7, 9, 8, 8, 7, 7, 7, 7, 7, 7, 7, 8, 9, 9, 7, 5, 10, 8, 9, 9, 4, 5, 9, 9, 5, 9, 6, 9, 6, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 9, 1, 1, 4, 9, 4, 7, 8, 9, 9, 7, 8, 8, 6, 7, 3, 8, 6, 8, 7, 8, 3, 6, 6, 9, 8, 7, 7, 6, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 3, 8, 8, 9, 9, 8, 8, 9, 9, 8, 9, 8, 8, 8, 8, 8, 8, 8, 3, 2, 8, 8, 8, 8, 8, 9, 9, 2, 9, 2, 1, 2, 8, 3, 8,

/tmp/ipykernel_2995/280982879.py:25: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  idx = np.where(x.labels == 0)
/tmp/ipykernel_2995/280982879.py:26: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  idx2 = np.where(labels[-1] == 0)


[ 1  2  3  4  5  6  7  8  9 10]
[9, 10, 10, 10, 9, 9, 9, 10, 10, 9, 10, 10, 10, 10, 10, 9, 10, 9, 10, 10, 10, 5, 5, 9, 9, 2, 5, 8, 5, 5, 5, 6, 6, 8, 5, 8, 8, 3, 7, 7, 7, 7, 7, 7, 9, 9, 7, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 7, 9, 1, 9, 10, 10, 5, 9, 8, 9, 9, 9, 9, 10, 6, 10, 10, 6, 9, 9, 9, 9, 8, 8, 8, 5, 3, 3, 9, 7, 6, 8, 2, 8, 8, 6, 2, 8, 8, 8, 2, 3, 1, 2, 5, 7, 2, 3, 4, 4, 8, 8, 5, 5, 8, 3, 8, 3, 3, 7, 7, 4, 7, 8, 2, 2, 2, 2, 2, 2, 8, 8, 3, 8, 8, 3, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 7, 9, 8, 2, 4, 3, 8, 9, 4, 3, 4, 8, 9, 8, 8, 8, 4, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 2, 1, 8, 1, 3, 8, 8, 8, 8, 9, 8, 1, 1, 8, 8, 1, 4, 8, 1, 9, 9, 9, 7, 8, 8, 9, 8, 7, 1, 9, 2, 2, 1, 9, 2, 9, 3, 3, 8, 3, 8, 7, 8, 8, 8, 8, 8, 8, 8, 2, 2, 3, 3, 3, 3, 9, 9, 9, 9, 9, 8, 7, 8, 8, 7, 2, 5, 6, 2, 6, 7, 6, 6, 5, 3, 7, 2, 6, 7, 6, 3, 8, 8, 8, 8, 8, 9, 6, 7, 6, 3, 6, 6, 6, 8, 6, 7, 8, 7, 9, 7, 8, 8, 2, 1, 2, 1, 7, 7, 7, 5, 2, 7, 10, 10, 10, 9, 4, 7, 6, 6, 2, 9, 9, 2, 9, 7, 9, 1, 9, 9, 1, 5, 3, 2, 9, 2, 9, 

/tmp/ipykernel_2995/280982879.py:30: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  idx = np.where(labels == 0)
/tmp/ipykernel_2995/280982879.py:31: DeprecationWarning: Calling nonzero on 0d arrays is deprecated, as it behaves surprisingly. Use `atleast_1d(cond).nonzero()` if the old behavior was intended. If the context of this warning is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.
  idx2 = np.where(tok_labels == 0)


In [ ]:
print(labels)

[[9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 8, 3, 1, 1, 1, 1, 7, 8, 8, 8, 8, 8, 8, 8, 1, 8, 8, 6, 8, 8, 8, 1, 8, 6, 6, 1, 8, 3, 5, 9, 9, 9, 9, 9, 9, 9, 1, 5, 7, 9, 5, 8, 10, 10, 10, 10, 10, 10, 10, 10, 6, 6, 10, 5, 6, 10, 10, 4, 10, 10, 6, 10, 10, 6, 6, 9, 9, 6, 7, 7, 5, 9, 9, 9, 9, 9, 9, 9, 1, 2, 8, 8, 5, 5, 8, 5, 4, 8, 5, 2, 10, 8, 8, 8, 8, 9, 9, 8, 4, 3, 3, 6, 5, 3, 6, 9, 2, 5, 8, 3, 7, 8, 4, 6, 8, 8, 8, 8, 6, 8, 3, 2, 8, 9, 8, 8, 7, 2, 7, 7, 8, 8, 9, 9, 8, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 4, 2, 6, 3, 3, 3, 1, 2, 2, 7, 4, 4, 6, 9, 6, 6, 9, 9, 1, 2, 7, 1, 2, 2, 8, 1, 8, 2, 2, 8, 8, 4, 8, 3, 8, 8, 9, 9, 7, 9, 8, 8, 7, 7, 7, 7, 7, 7, 7, 8, 9, 9, 7, 5, 10, 8, 9, 9, 4, 5, 9, 9, 5, 9, 6, 9, 6, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 9, 1, 1, 4, 9, 4, 7, 8, 9, 9, 7, 8, 8, 6, 7, 3, 8, 6, 8, 7, 8, 3, 6, 6, 9, 8, 7, 7, 6, 8, 8, 8, 8, 8, 8, 8, 8, 8, 2, 8, 8, 8, 3, 8, 8, 9, 9, 8, 8, 9, 9, 8, 9, 8, 8, 8, 8, 8, 8, 8, 3, 2, 8, 8, 8, 8, 8, 9, 9, 2, 9, 2, 1, 2, 8, 3, 8, 9, 9, 8, 8, 3, 3, 2, 3, 2, 3, 

In [ ]:
fin_labels = []
ftok_labels = []
for l in labels : 
    fin_labels += l
for l in tok_labels:
    ftok_labels += l

In [ ]:

    
fl = np.where(np.array(fin_labels) == 0)[0]
ftl = np.where(np.array(ftok_labels) ==0 )[0]
print(len(fl), len(ftl))
print(fl)
evaluate_indices(fl, ftl)

0 349
[]


(0.0, 0, 0)